# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from otus_graphql import books_pb2 as otus__graphql_dot_books__pb2


class BooksServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetBooks = channel.unary_stream(
                '/BooksService/GetBooks',
                request_serializer=otus__graphql_dot_books__pb2.Empty.SerializeToString,
                response_deserializer=otus__graphql_dot_books__pb2.Book.FromString,
                )


class BooksServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetBooks(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BooksServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetBooks': grpc.unary_stream_rpc_method_handler(
                    servicer.GetBooks,
                    request_deserializer=otus__graphql_dot_books__pb2.Empty.FromString,
                    response_serializer=otus__graphql_dot_books__pb2.Book.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'BooksService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class BooksService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetBooks(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/BooksService/GetBooks',
            otus__graphql_dot_books__pb2.Empty.SerializeToString,
            otus__graphql_dot_books__pb2.Book.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
